Tahoe style certs for PennState
appsembler/edx-theme-customers pull request #117
Opened 2020-06-17 18:17 UTC by bryanlandia

2020-06-17 18:53 UTC, bryanlandia commented
Updated to rebase off of unmerged amir/ginkgo.psu/BLACK-700 since @amirtds and I are both working on changes to push to staging

2020-06-17 19:28 UTC, amirtds requested changes

2020-06-17 19:28 UTC, amirtds commented on lms/templates/theme-variables.html
> +<%! from datetime import date %>
@bryanlandia I think this should be `<%! from datetime import datetime, date %>` We use `datetime.now()` to get current year https://github.com/appsembler/edx-theme-customers/blob/648708c85452717577b3e473ab57c4b9a0f4cb33/lms/templates/theme-variables.html#L166

2020-06-24 22:51 UTC, amirtds approved these changes
Thanks @bryanlandia It looks good. I checked quickly the staging server here https://learn.extension-dev.psu.edu/certificates/5cfe5a84c7074358adb2b516c544b9b3 and looks good

2020-06-24 23:37 UTC, bryanlandia commented
I'm not merging yet since we don't have any approval yet from PSU and don't want these deployed to prod accidentally.

2020-08-05 02:24 UTC, bryanlandia commented
@amirtds  I'm going to merge this in advance of probable production push Wednesday or Thursday of this week.  I rebased off of ginkgo/pennstate so it's got your latest changes.

2020-08-05 02:24 UTC, merged